title: the-forgotten-squad
description: "wsg gang its yo gurl leonsimp realest and guess what: she's back with some food for her tiny fandom! PS FANS REJOICEEE hehe anyways... this theme is dedicated to the prince series' forgotten squad! no, not just jayvyn, uthman, junta, and vladimir, but also dhaluu, jamil, shao long, and himawari!"
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]